<?php

namespace Database\Seeders;

use App\Models\Peixe;
use Illuminate\Database\Seeder;

class PeixeSeeder extends Seeder
{

    private $peixes = [
        ['nome_cientifico' => 'Abudefduf saxatilis', 'nome' => 'Oá', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Acanthostracion quadricornis', 'nome' => 'Peixe-cofre riscado', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Acanthostracion polygonius', 'nome' => 'Peixe-cofre colméia', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Acanthurus bahianus', 'nome' => 'Cirurgião', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Acanthurus chirurgus', 'nome' => 'Barbeiro comum', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Acanthurus coeruleus', 'nome' => 'Barbeiro azul', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Achirus lineatus', 'nome' => 'Aramaçá', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Alphestes afer', 'nome' => 'Garoupa-gato', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Aluterus schoepfi', 'nome' => 'Raquete laranja', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Aluterus scriptus', 'nome' => 'Raquete riscado', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Amblycirrhitus pinos', 'nome' => 'Peixe-gavião', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Anisotremus surinamensis', 'nome' => 'Sargo-de-beiço', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Anisotremus virginicus', 'nome' => 'Salema', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Antennarius striatus', 'nome' => 'Peixe-pescador riscado', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Apogon americanus', 'nome' => 'Apogon brasileiro', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Apogon pseudomaculatus', 'nome' => 'Apogon-de-duas-manchas', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Archosargus rhomboidalis', 'nome' => 'Canhanha', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Aulostomus strigosus', 'nome' => 'Peixe-trompete', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Bathygobius soporator', 'nome' => 'Emborê', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Batrachoides surinamensis', 'nome' => 'Pacamão', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Bodianus pulchellus', 'nome' => 'Bodião vermelho', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Bodianus rufus', 'nome' => 'Bodião azul', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Bothus lunatus', 'nome' => 'Linguadinho pavão', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Bothus ocellatus', 'nome' => 'Linguadinho ocelado', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Calamus pennatula', 'nome' => 'Pargo pena', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Cantherhines macrocerus', 'nome' => 'Peixe porco de pintas brancas', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Cantherhines pullus', 'nome' => 'Peixe porco de pintas laranja', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Canthigaster figueiredoi', 'nome' => 'Baiacú de recife', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Centropyge aurantonotus', 'nome' => 'Centropyge dorso de fogo', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Chaetodipterus faber', 'nome' => 'Enxada', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Chaetodon ocellatus', 'nome' => 'Borboleta ocelado', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Chaetodon sedentarius', 'nome' => 'Borboleta dos recifes', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Chaetodon striatus', 'nome' => 'Borboleta listrado', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Chilomycterus antennatus', 'nome' => 'Baiacú espinho antenado', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Chilomycterus antillarum', 'nome' => 'Baiacú espinho rendado', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Chromis multilineata', 'nome' => 'Cromis tesoura', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Cyclichthys spinosus', 'nome' => 'Baiacú espinho brasileiro', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Clepticus brasiliensis', 'nome' => 'Clepticus brasileiro', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Conodon nobilis', 'nome' => 'Roncador', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Coryphopterus glaucofraenum', 'nome' => 'Gobião de freio', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Cosmocampus albirostris', 'nome' => 'Peixe cachimbo de focinho branco', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Dactylopterus volitans', 'nome' => 'Coió', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Diodon holacanthus', 'nome' => 'Baiacú espinho manchado', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Diodon hystrix', 'nome' => 'Baiacú espinho pintalgado', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Diplectrum formosum', 'nome' => 'Michole da areia listrado', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Diplectrum radiale', 'nome' => 'Michole da areia costeiro', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Doratonotus megalepis', 'nome' => 'Sabonete anão', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Dules auriga', 'nome' => 'Mariquita de penacho', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Echeneis naucrates', 'nome' => 'Rêmora de listra negra', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Fistularia tabacaria', 'nome' => 'Trombeta pintada', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Gobiesox strumosus', 'nome' => 'Peixe ventosa vermiculado', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Gymnachirus nudus', 'nome' => 'Linguado zebra', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Gymnothorax funebris', 'nome' => 'Moréia verde', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Gymnothorax miliaris', 'nome' => 'Moréia rabo dourado', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Gymnothorax moringa', 'nome' => 'Moréia pintada', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Gymnothorax ocellatus', 'nome' => 'Moréia ocelada', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Gymnothorax vicinus', 'nome' => 'Moréia boca roxa', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Haemulon steindachneri', 'nome' => 'Quatinga', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Halichoeres bivittatus', 'nome' => 'Sabonete listrado', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Halichoeres brasiliensis', 'nome' => 'Sabonete brasileiro', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Halichoeres cyanocephalus', 'nome' => 'Sabonete cara amarela', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Halichoeres maculipinna', 'nome' => 'Sabonete ocelado', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Halichoeres poeyi', 'nome' => 'Sabonete verde', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Heteropriacanthus cruentatus', 'nome' => 'Olho de cão das pedras', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Hippocampus erectus', 'nome' => 'Cavalo marinho de focinho curto', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Hippocampus reidi', 'nome' => 'Cavalo marinho de focinho longo', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Holacanthus ciliaris', 'nome' => 'Ciliaris', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Holacanthus tricolor', 'nome' => 'Tricolor', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Holocentrus adscensionis', 'nome' => 'Jaguariçá', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Kyphosus incisor', 'nome' => 'Piragica amarela', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Kyphosus sectatrix', 'nome' => 'Piragica comum', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Labrisomus nuchipinnis', 'nome' => 'Maria-da-toca', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Lactophrys trigonus', 'nome' => 'Peixe cofre', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Lagocephalus laevigatus', 'nome' => 'Baiacú arara', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Melichthys niger', 'nome' => 'Cangulo preto', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Menticirrhus americanus', 'nome' => 'Papa terra', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Micropogonias furnieri', 'nome' => 'Corvina marisqueira', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Mulloidichthys martinicus', 'nome' => 'Trilha amarela', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Mullus argentinae', 'nome' => 'Trilha', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Muraena pavonina', 'nome' => 'Moréia de pintas brancas', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Myrichthys ocellatus', 'nome' => 'Murucutuca ocelada', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Myrichthys breviceps', 'nome' => 'Murucutuca pintada', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Myripristis jacobus', 'nome' => 'Fogueira', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Odontoscion dentex', 'nome' => 'Corvina dos recifes', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Ogcocephalus vespertilio', 'nome' => 'Peixe morcego do focinho longo', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Oligoplites saliens', 'nome' => 'Xaveia', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Ophioblennius trinitatis', 'nome' => 'Maria-da-toca oceânico', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Orthopristis ruber', 'nome' => 'Corcoroca jurumirim', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Parablennius marmoreus', 'nome' => 'Maria-da-toca das algas', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Parablennius pilicornis', 'nome' => 'Maria-da-toca das pedras', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Paraclinus rubicundus', 'nome' => 'Macaco verde', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Paralonchurus brasiliensis', 'nome' => 'Cabeça-de-côco', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Paranthias furcifer', 'nome' => 'Boquinha', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Pareques acuminatus', 'nome' => 'Anteninha', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Pempheris schomburgki', 'nome' => 'Olhudo', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Phaeoptyx pigmentaria', 'nome' => 'Apogon pintado', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Plectrypops retrospinis', 'nome' => 'Soldado', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Pomacanthus arcuatus', 'nome' => 'Frade cinza', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Pomacanthus paru', 'nome' => 'Frade', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Pomadasys corvinaeformis', 'nome' => 'Corcoroca legítima', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Porichthys porosissimus', 'nome' => 'Mamangava', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Prionotus nudigula', 'nome' => 'Cabrinha comum', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Rypticus bistrispinus', 'nome' => 'Badejo sabão pintalgado', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Rypticus saponaceus', 'nome' => 'Badejo sabão comum', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Scarus zelindae', 'nome' => 'Peixe papagaio Zelinda', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Scorpaena brasiliensis', 'nome' => 'Beatinha pintada', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Scorpaena isthmensis', 'nome' => 'Beatinha cara-lisa', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Scorpaena plumieri', 'nome' => 'Beatinha axila-roxa', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Selene vomer', 'nome' => 'Peixe-galo', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Serranus baldwini', 'nome' => 'Badejinho lanterna', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Serranus flaviventris', 'nome' => 'Mariquita', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Serranus phoebe', 'nome' => 'Sete-fundão', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Sparisoma amplum', 'nome' => 'Peixe papagaio dos recifes', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Sparisoma axillare', 'nome' => 'Peixe papagaio cinzento', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Sparisoma radians', 'nome' => 'Peixe papagaio dentuço', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Sparisoma frondosum', 'nome' => 'Peixe papagaio sinaleiro', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Sphoeroides greeleyi', 'nome' => 'Baiacú verde', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Sphoeroides spengleri', 'nome' => 'Baiacú pinima', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Sphoeroides testudineus', 'nome' => 'Baiacú quadriculado', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Stegastes fuscus', 'nome' => 'Castanheta', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Stegastes pictus', 'nome' => 'Donzela bicolor', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Stegastes uenfi', 'nome' => 'Donzela cinza', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Stegastes variabilis', 'nome' => 'Donzela amarela', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Stephanolepis hispidus', 'nome' => 'Porquinho de fronte reta', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Stephanolepis setifer', 'nome' => 'Porquinho de penacho', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Stygnobrotula latebricola', 'nome' => 'Brotula negra', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Synodus foetens', 'nome' => 'Peixe-lagarto costeiro', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Synodus intermedius', 'nome' => 'Peixe-lagarto de areia', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Synodus synodus', 'nome' => 'Peixe lagarto vermelho', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Thalassoma noronhanum', 'nome' => 'Sabonete das ilhas', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Thalassophryne montevidensis', 'nome' => 'Niquim barrado', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Thalassophryne nattereri', 'nome' => 'Niquim comum', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Trachinocephalus myops', 'nome' => 'Peixe-cobra', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Upeneus parvus', 'nome' => 'Trilha pena', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Xyrichthys novacula', 'nome' => 'Budião de areia', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Xyrichthys splendens', 'nome' => 'Peixe-dragão verde', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Centropomus undecimalis', 'nome' => 'Robalo flecha', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Centropomus parallelus', 'nome' => 'Robalo peva', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Megalops Atlanticus', 'nome' => 'Tarpon', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Lutjanus cyanopterus', 'nome' => 'Caranha', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Genidens genidens', 'nome' => 'Bagre do mar', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Cathorops spixii', 'nome' => 'Bagre amarelo', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Cynoscion acoupa', 'nome' => 'Pescada amarela', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Lutjanus analis', 'nome' => 'Cioba', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Acanthocybium solandri', 'nome' => 'Cavala', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Sphyraena barracuda', 'nome' => 'Barracuda', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Oligoplites saurus', 'nome' => 'Tibiro', 'habitat' => 'Marinho'],
        ['nome_cientifico' => 'Pterodoras granulosus', 'nome' => 'Abotoado ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Geophagus brasiliensis', 'nome' => 'Acará ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Pterophyllum scalare', 'nome' => 'Acará-Bandeira ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Symphysodon aequifasciatus', 'nome' => 'Acará-Disco ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Osteoglossum bicirhossum', 'nome' => 'Aruanã ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Astronotus ocellatus', 'nome' => 'Apaiari ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Pellona castelnaeana', 'nome' => 'Apapá ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Henochilus wheatlandii', 'nome' => 'Andirá ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Pinirampus pinirampu', 'nome' => 'Barbado ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Phalloceros caudimaculatus', 'nome' => 'Barrigudinho ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Boulengerella maculata', 'nome' => 'Bicuda ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Pseudoplathystoma fasciatum', 'nome' => 'Cachara ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Hydrolycus scomberoides', 'nome' => 'Cachorra ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Vandellia cirrhosa', 'nome' => 'Candiru ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Pseudoplatystoma tigrinum', 'nome' => 'Surubim', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Hypostomus affinis', 'nome' => 'Cascudo ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Plagioscion squamosissimus', 'nome' => 'Corvina ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Prochilodus lineatus', 'nome' => 'Curimbatá ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Salminus maxillosus', 'nome' => 'Dourado ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Brachyplatystoma flavicans', 'nome' => 'Dourada ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Paulicea luetkeni', 'nome' => 'Jaú ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Crenicichla lenticulata', 'nome' => 'Jacundá ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Rhamdia quelen', 'nome' => 'Jundiá ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Hemisorubim platyrhynchos', 'nome' => 'Jurupoca ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Sorubim lima', 'nome' => 'Jurupensém ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Astyanax bimaculatus', 'nome' => 'Lambari ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Corydoras paleatus', 'nome' => 'Limpa-Fundo ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Pimelodus maculatus', 'nome' => 'Mandi ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Ageneiosus brevifilis', 'nome' => 'Mandubé ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Hyphessobrycon eques', 'nome' => 'Mato-Grosso ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Brycon cephalus', 'nome' => 'Matrinxã ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Synbranchus marmoratus', 'nome' => 'Mussum ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Paracheirodon axelrodi', 'nome' => 'Neon ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Piaractus mesopotamicus', 'nome' => 'Pacu ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Austrolebias minuano', 'nome' => 'Peixe-Anual ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Carnegiella strigata', 'nome' => 'Peixe-Borboleta ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Rhaphiodon vulpinus', 'nome' => 'Peixe-Cachorro ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Leporinus freiderici', 'nome' => 'Piau-Três-Pintas ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Brycon insignis', 'nome' => 'Piabanha ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Leporinus macrocephalus', 'nome' => 'Piavuçu ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Pseudoplatystoma corruscans', 'nome' => 'Pintado ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Brycon orbignyanus', 'nome' => 'Piracanjuba ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Platynematichthys notatus', 'nome' => 'Piranambu ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Serrasalmus rhombeus', 'nome' => 'Piranha Preta ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Pygocentrus nattereri', 'nome' => 'Piranha Vermelha ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Piaractus brachypomus', 'nome' => 'Pirapitinga ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Phractocephalus hemeliopterus', 'nome' => 'Pirarara ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Brachyplatystoma filamentosum', 'nome' => 'Piraíba ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Brycon microlepis', 'nome' => 'Piraputanga ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Arapaima gigas', 'nome' => 'Pirarucu ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Electrophorus electricus', 'nome' => 'Poraquê ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Anableps anableps', 'nome' => 'Quatro-Olhos ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Potamotrygon falkneri', 'nome' => 'Raia ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Cyphocarax gilbert', 'nome' => 'Saguiru ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Acestrorrynchus hepsetus', 'nome' => 'Saicanga ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Gymnotus carapo', 'nome' => 'Sarapó ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Colossoma macropomum', 'nome' => 'Tambaqui ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Tilapia rendalli', 'nome' => 'Tilápia ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Hoplias malabaricus', 'nome' => 'Traíra ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Hoplias lacerdae', 'nome' => 'Trairão ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Salmo trutta fario', 'nome' => 'Truta Comum ', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Cichla ocellaris', 'nome' => 'Tucunaré borboleta', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Cichla nigromaculata', 'nome' => 'Tucunaré tauá', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Cichla monoculus', 'nome' => 'Tucunaré popoca', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Cichla kelberi ', 'nome' => 'Tucunaré amarelo', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Cichla pleiozona', 'nome' => 'Tucunaré pitanga', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Cichla piquiti', 'nome' => 'Tucunaré azul', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Cichla pinima', 'nome' => 'Tucunaré pinima', 'habitat' => 'Água doce'],
        ['nome_cientifico' => 'Cichla temensis', 'nome' => 'Tucunaré açu', 'habitat' => 'Água doce'],
    ];

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Peixe::insert($this->peixes);
    }
}
